feature/maint 20240909
robert-koch-institut/mex-template pull request #71
Opened 2024-09-09 08:20 UTC by cutoffthetop

# PR Context

# Added

# Changes
- update requirements and github-actions

# Deprecated

# Removed

# Fixed

# Security

2024-09-12 08:21 UTC, rababerladuseladim requested changes
Nice, only one remark.

2024-09-12 08:21 UTC, rababerladuseladim commented on mex-{{ cookiecutter.project_name }}/.github/workflows/release.yml
I am pretty sure that lines 128-131 should look like this:
```
          docker build . \
            --tag ghcr.io/robert-koch-institut/mex-{{ cookiecutter.project_name }}:latest \
            --tag ghcr.io/robert-koch-institut/mex-{{ cookiecutter.project_name }}:{% raw %}${{ github.sha }}{% endraw %} \
            --tag ghcr.io/robert-koch-institut/mex-{{ cookiecutter.project_name }}:{% raw %}${{ needs.release.outputs.tag}}{% endraw %}
```
Otherwise the `--tag` is interpreted as separate command.

2024-09-13 08:30 UTC, cutoffthetop commented on mex-{{ cookiecutter.project_name }}/.github/workflows/release.yml
oh, yes! https://github.com/robert-koch-institut/mex-template/pull/71/commits/7b400d3849e267ead47c57f76a75d6a7fb169d06

2024-09-13 09:43 UTC, rababerladuseladim approved these changes

2024-09-13 10:09 UTC, merged