feature/template-maintenance
robert-koch-institut/mex-template pull request #75
Opened 2024-09-16 14:04 UTC by cutoffthetop

# Changes
- clarify release step names
- make python bound order consistent with deps
- add PNGs to ignore files (for playwright testing)
- update versions

2024-10-07 09:32 UTC, rababerladuseladim requested changes
Only one question.

2024-10-07 09:32 UTC, rababerladuseladim commented on .gitignore
> +tests/
doesn't this ignore all changes to tests?

2024-10-07 09:32 UTC, rababerladuseladim commented on mex-{{ cookiecutter.project_name }}/.gitignore
> +tests/
same as above: doesn't this ignore all changes to tests?

2024-10-10 13:15 UTC, cutoffthetop commented on .gitignore
> +tests/
sorry, yeah. that was a copy&paste mistake from the dockerignore

2024-10-10 13:16 UTC, cutoffthetop commented on mex-{{ cookiecutter.project_name }}/.gitignore
> +tests/
fixed

2024-10-11 07:04 UTC, rababerladuseladim approved these changes

2024-10-11 07:09 UTC, merged